services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    # networks:
    #   - app-network

  frontend:
    build: ./frontend
    ports:
      - "8080:5173"
    depends_on:
      - backend
    # networks:
    #   - app-network

#   db:
#     image: postgres:14
#     environment:
#       - POSTGRES_USER=user
#       - POSTGRES_PASSWORD=pass
#       - POSTGRES_DB=mydb
#     volumes:
#       - dbdata:/var/lib/postgresql/data
#     networks:
#       - app-network

# volumes:
#   dbdata:

# networks:
#   app-network:
