services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    networks:
      - app-network

  vue-app:
    build: ./path-to-vue-app
    ports:
      - "8080:80" # Map port 8080 on host to port 80 in the container
    networks:
      - app-network

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=mydb
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
