services:
  vue-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8081:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
  vue-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production