FROM oven/bun:latest as BUILD

WORKDIR /app

# Copy the rest of the application code
COPY package.json bun.lockb .

# Install dependencies
RUN bun install --frozen-lockfile

ENV PATH /app/node_movules/.bin:$PATH

COPY . .

RUN bun run build

FROM nginx:stable-alpine

COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /var/www/html/

EXPOSE 8080

ENTRYPOINT ["nginx","-g","daemon off;"]